vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set list")
vim.cmd("set mouse=")
vim.cmd("set nowrap")
vim.cmd("set linebreak")
vim.cmd("set scrolloff=4")
vim.cmd("set nohls")
vim.cmd("let c_no_curly_error=1")
vim.cmd("set signcolumn=yes:1")
vim.cmd("let g:netrw_banner = 0")
require('alex')
